name: Ffml-processing Deployment

on:
  push:
    branches:
      - dev
      - dev-lambda-*
      - main

jobs:
  deploy:
    environment: ${{ startsWith(github.ref_name, 'main-') && 'main' || startsWith(github.ref_name, 'dev-') && 'dev' || github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy
        run: |
          source venv/bin/activate
          zappa update ${{ startsWith(github.ref_name, 'main-') && 'main' || startsWith(github.ref_name, 'dev-') && 'dev' || github.ref_name }}
